Select available state services from vehicles list
bimmerconnected/bimmer_connected pull request #213
Opened 2020-10-24 16:53 UTC by rikroe

## Proposed change

This PR adds code that checks for available `state` services from the base vehicles list. If one's car is to old to support e.g. `statistics`, calling the endpoint will return an empty list. However the additional network traffic/waiting time is unecessary.

Also, cars `conventional` engines only seem not to be able to call the `efficiency` and `navigation` endpoints. In case of a conventional car, they even return `403` errors, rising exceptions.
__Please test this with your cars thoroughly, I don't know if another selection would be fitting better!__

@gerard33, @Markinus, @netdata-be, could you please verify this is working as expected?

## Type of change
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to this library)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [X] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue: 

## Checklist

- [X] The code change is tested and works locally.
- [X] Tests have been added to verify that the new code works.

2020-10-24 19:15 UTC, Markinus commented
Hi,
I like the Idea but we could do it in a different way, a suggestion only:
- I would suggest to check against != "NOT_SUPPORTED"
- We could add a validate attribute for all services, except vehicle, and check the availability of the services directly in the update procedure. Like:
state.py in __init__
       self._check_atribute = {
            SERVICE_STATUS: 'model', -> only a dummy because always available
            SERVICE_LAST_TRIP: 'statisticsAvailable',
            SERVICE_ALL_TRIPS: 'statisticsAvailable',
            SERVICE_CHARGING_PROFILE: 'chargingControl',
            SERVICE_DESTINATIONS: 'lastDestinations',
            SERVICE_RANGEMAP: 'rangeMap',
            SERVICE_EFFICIENCY: 'chargingControl', -> NOT_SUPPORTED if not an EV or PHEV
            SERVICE_NAVIGATION: 'chargingControl'} -> NOT_SUPPORTED if not an EV or PHEV

As next exchange the for loop in update_data for check of these attributes. We would reduce the network data and the arrays would be always empty if a service is not supported.

What do you think?
Bye

2020-10-30 23:29 UTC, gerard33 commented
Here is my fingerprint done from master (incl. #219).

[ALL_TRIPS_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/5468111/ALL_TRIPS_0.txt)
[CHARGING_PROFILE_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/5468112/CHARGING_PROFILE_0.txt)
[DESTINATIONS_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/5468113/DESTINATIONS_0.txt)
[LAST_TRIP_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/5468114/LAST_TRIP_0.txt)
[STATUS_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/5468115/STATUS_0.txt)
[vehicles_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/5468116/vehicles_0.txt)

2020-10-30 23:30 UTC, gerard33 commented
And here is the fingerprint with this PR #213.

[STATUS_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/5468119/STATUS_0.txt)
[vehicles_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/5468120/vehicles_0.txt)

2020-11-01 11:30 UTC, EddyK69 approved these changes

2020-11-01 21:57 UTC, gerard33 requested changes

2020-11-01 21:57 UTC, gerard33 commented on bimmer_connected/state.py
> +        Get the timestamp when the data was recorded."""
```suggestion
        Get the timestamp when the data was recorded.
        """
```

2020-11-01 21:57 UTC, gerard33 commented on bimmer_connected/state.py
> +        Get all lids (doors+hatch+trunk) of the car."""
```suggestion
        Get all lids (doors+hatch+trunk) of the car.
        """
```

2020-11-01 21:57 UTC, gerard33 commented on bimmer_connected/state.py
> +        Get all open lids of the car."""
```suggestion
        Get all open lids of the car.
        """
```

2020-11-01 21:57 UTC, gerard33 commented on bimmer_connected/state.py
> +        Check if all lids are closed."""
```suggestion
        Check if all lids are closed.
        """
```

2020-11-01 21:57 UTC, gerard33 commented on bimmer_connected/state.py
> +        Get all windows (doors+sun roof) of the car."""
```suggestion
        Get all windows (doors+sun roof) of the car.
        """
```

2020-11-01 21:57 UTC, gerard33 commented on bimmer_connected/state.py
> +        Get all open windows of the car."""
```suggestion
        Get all open windows of the car.
        """
```

2020-11-01 21:57 UTC, gerard33 commented on bimmer_connected/state.py
> +        Check if all windows are closed."""
```suggestion
        Check if all windows are closed.
        """
```

2020-11-01 21:57 UTC, gerard33 commented on bimmer_connected/state.py
> +        Get state of the door locks."""
```suggestion
        Get state of the door locks.
        """
```

2020-11-01 21:57 UTC, gerard33 commented on bimmer_connected/state.py
> +        The reason for the last state update"""
```suggestion
        The reason for the last state update.
        """
```

2020-11-01 21:57 UTC, gerard33 commented on bimmer_connected/state.py
> +        Get the last charging end result"""
```suggestion
        Get the last charging end result.
        """
```

2020-11-01 21:57 UTC, gerard33 commented on bimmer_connected/state.py
> +        Get status of the connection"""
```suggestion
        Get status of the connection.
        """
```

2020-11-01 21:57 UTC, gerard33 commented on bimmer_connected/state.py
> +        Get status of the condition based services."""
```suggestion
        Get status of the condition based services.
        """
```

2020-11-01 21:57 UTC, gerard33 commented on bimmer_connected/state.py
> +        Check if the status of all condition based services is "OK"."""
```suggestion
        Check if the status of all condition based services is "OK".
        """
```

2020-11-01 21:57 UTC, gerard33 commented on bimmer_connected/state.py
> +        Remaining range on battery, in kilometers."""
```suggestion
        Remaining range on battery, in kilometers.
        """
```

2020-11-01 21:57 UTC, gerard33 commented on bimmer_connected/state.py
> +        That is electrical range + fuel range."""
```suggestion
        That is electrical range + fuel range.
        """
```

2020-11-01 21:57 UTC, gerard33 commented on bimmer_connected/state.py
> +        This can change with driving style and temperature in kilometers."""
```suggestion
        Get the maximum electric range in kilometers.
        This can change with driving style and temperature.
        """
```

2020-11-01 21:57 UTC, gerard33 commented on bimmer_connected/state.py
> +        Charging state of the vehicle."""
```suggestion
        Charging state of the vehicle.
        """
```

2020-11-01 21:57 UTC, gerard33 commented on bimmer_connected/state.py
> +        Get the remaining charging time."""
```suggestion
        Get the remaining charging time.
        """
```

2020-11-01 21:57 UTC, gerard33 commented on bimmer_connected/state.py
> +        State of charge of the high voltage battery in percent."""
```suggestion
        State of charge of the high voltage battery in percent.
        """
```

2020-11-01 21:57 UTC, gerard33 commented on bimmer_connected/state.py
> +        List of check control messages."""
```suggestion
        List of check control messages.
        """
```

2020-11-01 21:57 UTC, gerard33 commented on bimmer_connected/state.py
> +        Return true if any check control message is present."""
```suggestion
        Return true if any check control message is present.
        """
```

2020-11-01 22:16 UTC, gerard33 commented on bimmer_connected/state.py
> +        This can change with driving style and temperature in kilometers.
```suggestion
        Maximum range on battery, in kilometers.
        This can change with driving style and temperature.
```

2020-11-01 22:24 UTC, gerard33 approved these changes

2020-11-01 22:27 UTC, merged