Update vehicle_status.py
bimmerconnected/bimmer_connected pull request #262
Opened 2021-01-11 00:35 UTC by luka6000

## Proposed change

there seem to be additional position states, like LAST_KNOWN so changed the bool condition to include DRIVER_DISABLED as actual indication of vehicle tracking being disabled.

## Type of change
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to this library)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #261 
- This PR is related to issue: 

## Checklist

- [x] The code change is tested and works locally.
- [ ] Tests have been added to verify that the new code works.

2021-01-11 07:07 UTC, gerard33 approved these changes
Thanks

2021-01-11 19:24 UTC, rikroe requested changes
Thanks! Please adjust for TOO_FAR_AWAY, then we're good 👍

2021-01-11 19:24 UTC, rikroe commented on bimmer_connected/vehicle_status.py
> +        return self._state.attributes[SERVICE_STATUS]['position']['status'] != 'DRIVER_DISABLED'
```suggestion
        return self._state.attributes[SERVICE_STATUS]['position']['status'] not in ['DRIVER_DISABLED', 'TOO_FAR_AWAY']
```
Please also include `TOO_FAR_AWAY` for older vehicles (if the location of the smartphone/bimmer_connected is >2km from the vehicle).

2021-01-12 07:22 UTC, rikroe approved these changes
LGTM

2021-01-12 07:24 UTC, merged